name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20, 22]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: corepack enable

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright-core install --with-deps chromium

      - name: Prepare
        run: pnpm dev:prepare

      - name: Build module
        run: pnpm prepack

      - name: Lint
        run: pnpm lint
        if: matrix.node == 22

      - name: Test types
        run: pnpm test:types

      - name: Test unit
        run: npx vitest run test/unit

      - name: Test integration
        run: npx vitest run test/integration

      - name: Test E2E
        run: npx vitest run test/e2e

      - name: Test performance
        run: npx vitest run test/performance
        if: matrix.node == 22
