name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Manually update npm to 11.5.1 or later which is the required version for trusted publishing to work # this step can be removed after the ubuntu runner has the correct minimum version of npm installed
        run: npm install -g npm@latest

      - run: corepack enable

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare development environment
        run: pnpm dev:prepare

      - name: Build module
        run: pnpm prepack

      - name: Publish to npm
        run: |
          if [[ "${{ github.ref }}" == *"-beta"* ]]; then
            npm publish --access public --tag beta
          elif [[ "${{ github.ref }}" == *"-alpha"* ]]; then
            npm publish --access public --tag alpha
          elif [[ "${{ github.ref }}" == *"-rc"* ]]; then
            npm publish --access public --tag rc
          else
            npm publish --access public
          fi

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes-file CHANGELOG.md \
            ${{ (contains(github.ref, '-beta') || contains(github.ref, '-alpha') || contains(github.ref, '-rc')) && '--prerelease' || '' }}
