name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Run linter
        run: pnpm lint

      - name: Build module
        run: pnpm prepack

      - name: Publish to npm
        run: |
          if [[ "${{ github.ref }}" == *"-beta"* ]]; then
            npm publish --provenance --tag beta
          elif [[ "${{ github.ref }}" == *"-alpha"* ]]; then
            npm publish --provenance --tag alpha
          else
            npm publish --provenance
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SAF_NPM_TOKEN }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes-file CHANGELOG.md \
            ${{ contains(github.ref, '-beta') || contains(github.ref, '-alpha') && '--prerelease' || '' }}